using WorkshopAssignment.Models;
using WorkshopAssignment.Services;
using Xunit;

namespace WorkshopAssignment.Tests;

public class DataServiceTests
{
    private readonly DataService _svc = new();

    // ---------------------------------------------------------------
    //  Helper: quick workshop constructors
    // ---------------------------------------------------------------
    private static Workshop W(string id, WorkshopType type, int cap = 20)
        => new(id, $"Workshop {id}", type, cap);

    private static Person P(string id, List<string> preferences, string? friendId = null)
        => new(id, $"Person {id}", preferences, friendId);

    /// <summary>
    /// Shorthand for creating a preference list from individual workshop IDs.
    /// Usage: Prefs("W2", "W3", "W4", "W1", "W5", "W6") returns List&lt;string&gt; with 6 ranked preferences.
    /// </summary>
    private static List<string> Prefs(params string[] ids)
        => ids.ToList();

    // ---------------------------------------------------------------
    //  1. BuildAssignmentInput — Valid Input
    // ---------------------------------------------------------------
    [Fact]
    public void BuildAssignmentInput_ValidInput_ReturnsResult()
    {
        var workshops = TestHelpers.StandardWorkshops();
        var persons = TestHelpers.StandardPersons();

        var result = _svc.BuildAssignmentInput(workshops, persons);

        Assert.NotNull(result);
        Assert.NotNull(result.InputData);
        Assert.Equal(workshops.Count, result.InputData.Workshops.Count);
        Assert.Equal(persons.Count, result.InputData.Persons.Count);
        Assert.NotEmpty(result.InputData.FriendGroups);

        // P1 and P2 are mutual friends -> should be in one group
        var groupWithP1 = result.InputData.FriendGroups
            .FirstOrDefault(g => g.MemberIds.Contains("P1"));
        Assert.NotNull(groupWithP1);
        Assert.Contains("P2", groupWithP1.MemberIds);
    }

    // ---------------------------------------------------------------
    //  2. BuildAssignmentInput — Empty Input
    // ---------------------------------------------------------------
    [Fact]
    public void BuildAssignmentInput_EmptyInput_ReturnsEmpty()
    {
        var result = _svc.BuildAssignmentInput([], []);

        Assert.NotNull(result);
        Assert.Empty(result.InputData.Workshops);
        Assert.Empty(result.InputData.Persons);
        Assert.Empty(result.InputData.FriendGroups);
        // Empty input to DataService does not generate warnings
        // (EmptySheet warnings are generated by ExcelService during file load, not here)
        Assert.Empty(result.Warnings);
    }

    // ---------------------------------------------------------------
    //  3. FriendGroups — Simple Pair Resolved
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_SimplePair_Resolved()
    {
        var workshops = new List<Workshop> { W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3), W("W4", WorkshopType.Type4) };
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4"), friendId: "A"),
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Should be exactly one group of 2
        Assert.Single(result.InputData.FriendGroups);
        var group = result.InputData.FriendGroups[0];
        Assert.Equal(2, group.MemberIds.Count);
        Assert.Contains("A", group.MemberIds);
        Assert.Contains("B", group.MemberIds);
    }

    // ---------------------------------------------------------------
    //  4. FriendGroups — Chain A-B-C
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_Chain_ABC()
    {
        var workshops = new List<Workshop> { W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3), W("W4", WorkshopType.Type4) };
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4"), friendId: "C"),
            P("C", Prefs("W2", "W3", "W4")),
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Non-mutual friend references now result in solo groups
        // A->B is not mutual (B->C), B->C is not mutual (C has no friend)
        Assert.Equal(3, result.InputData.FriendGroups.Count);
        Assert.All(result.InputData.FriendGroups, g => Assert.Single(g.MemberIds));
        // Warnings for non-mutual references
        Assert.Contains(result.Warnings, w => w.Category == WarningCategory.NonMutualFriend);
    }

    // ---------------------------------------------------------------
    //  5. FriendGroups — Circular Pair (no infinite loop)
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_CircularPair_Resolved()
    {
        var workshops = new List<Workshop> { W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3), W("W4", WorkshopType.Type4) };
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4"), friendId: "A"),
        };

        // Should complete without infinite loop and produce a group of 2
        var result = _svc.BuildAssignmentInput(workshops, persons);

        Assert.Single(result.InputData.FriendGroups);
        Assert.Equal(2, result.InputData.FriendGroups[0].MemberIds.Count);
        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.OversizedGroup);
    }

    // ---------------------------------------------------------------
    //  6. FriendGroups — Self Reference (A->A)
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_SelfReference_Warning()
    {
        // DataService's BFS: A has FriendId="A". When processing A, FriendId "A" is already
        // visited, so it's a no-op. A ends up as a solo group.
        // Note: DataService does NOT emit SelfReference warnings — that is the ExcelService's job.
        // DataService treats self-ref as effectively "no friend" since BFS skips already-visited.
        var workshops = new List<Workshop> { W("W1", WorkshopType.Type1), W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3) };
        var persons = new List<Person>
        {
            P("A", Prefs("W1", "W2", "W3"), friendId: "A"),
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // A becomes a solo group
        Assert.Single(result.InputData.FriendGroups);
        Assert.Single(result.InputData.FriendGroups[0].MemberIds);
        Assert.Equal("A", result.InputData.FriendGroups[0].MemberIds[0]);
    }

    // ---------------------------------------------------------------
    //  7. FriendGroups — Cross-File References
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_CrossFileRefs_Resolved()
    {
        // Simulates persons from different files: A references B by ID
        var workshops = new List<Workshop> { W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3), W("W4", WorkshopType.Type4) };
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4")),  // B has no friendId — came from a different file
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Non-mutual friend references now result in solo groups
        // A->B is not mutual (B has no friendId)
        Assert.Equal(2, result.InputData.FriendGroups.Count);
        Assert.All(result.InputData.FriendGroups, g => Assert.Single(g.MemberIds));
        // Warning for non-mutual reference
        Assert.Contains(result.Warnings, w => w.Category == WarningCategory.NonMutualFriend);
    }

    // ---------------------------------------------------------------
    //  8. FriendGroups — Oversized Group Split
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_OversizedGroup_Split()
    {
        var workshops = new List<Workshop> { W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3), W("W4", WorkshopType.Type4) };
        // Chain: A->B->C->D = non-mutual friend references
        // A->B (B doesn't reference A), B->C (C doesn't reference B), C->D (D has no reference)
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4"), friendId: "C"),
            P("C", Prefs("W2", "W3", "W4"), friendId: "D"),
            P("D", Prefs("W2", "W3", "W4")),
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Non-mutual friend references result in 4 individual solo groups
        Assert.Equal(4, result.InputData.FriendGroups.Count);
        Assert.All(result.InputData.FriendGroups, g => Assert.Single(g.MemberIds));
        // Non-mutual references generate NonMutualFriend warnings (not OversizedGroup)
        Assert.Contains(result.Warnings, w => w.Category == WarningCategory.NonMutualFriend);
    }

    // ---------------------------------------------------------------
    //  9. FriendGroups — Reverse Lookup
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_ReverseLookup()
    {
        // A references B, but B has no FriendId. Non-mutual friend detection now applies.
        var workshops = new List<Workshop> { W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3), W("W4", WorkshopType.Type4) };
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4")),  // no friend-id set
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Non-mutual friend references now result in solo groups
        // A->B is not mutual (B has no friendId pointing back to A)
        Assert.Equal(2, result.InputData.FriendGroups.Count);
        Assert.All(result.InputData.FriendGroups, g => Assert.Single(g.MemberIds));
        // Warning for non-mutual reference
        Assert.Contains(result.Warnings, w => w.Category == WarningCategory.NonMutualFriend);
    }

    // ---------------------------------------------------------------
    // 10. FriendGroups — No Friends, All Solo
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_NoFriends_AllSolo()
    {
        var workshops = new List<Workshop> { W("W1", WorkshopType.Type1), W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3) };
        var persons = new List<Person>
        {
            P("A", Prefs("W1", "W2", "W3")),
            P("B", Prefs("W1", "W2", "W3")),
            P("C", Prefs("W1", "W2", "W3")),
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        Assert.Equal(3, result.InputData.FriendGroups.Count);
        Assert.All(result.InputData.FriendGroups, g => Assert.Single(g.MemberIds));
    }

    // ---------------------------------------------------------------
    // 11. FriendGroups — Invalid Friend Reference
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_InvalidFriendRef_Warning()
    {
        var workshops = new List<Workshop> { W("W1", WorkshopType.Type1), W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3) };
        var persons = new List<Person>
        {
            P("A", Prefs("W1", "W2", "W3"), friendId: "Z"),  // Z doesn't exist
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // A becomes solo group, with InvalidFriend warning
        Assert.Single(result.InputData.FriendGroups);
        Assert.Single(result.InputData.FriendGroups[0].MemberIds);
        Assert.Equal("A", result.InputData.FriendGroups[0].MemberIds[0]);
        Assert.Contains(result.Warnings, w => w.Category == WarningCategory.InvalidFriend);
        Assert.Contains(result.Warnings, w => w.Message.Contains("Z"));
    }

    // ---------------------------------------------------------------
    // 12. FriendGroups — Preference Pooling (Union with Best Rank)
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_PreferencePooling_UnionWithBestRank()
    {
        var workshops = new List<Workshop>
        {
            W("W2", WorkshopType.Type2),
            W("W3", WorkshopType.Type3),
            W("W4", WorkshopType.Type4),
            W("W5", WorkshopType.Type2),
        };
        var persons = new List<Person>
        {
            // A's preferences: W2 (rank 0), W3 (rank 1), W4 (rank 2)
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            // B's preferences: W3 (rank 0), W4 (rank 1), W5 (rank 2)
            P("B", Prefs("W3", "W4", "W5"), friendId: "A"),
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        Assert.Single(result.InputData.FriendGroups);
        var group = result.InputData.FriendGroups[0];

        // Pooled preferences: union of all unique workshop IDs, sorted by best rank.
        // W2: only in A at rank 0 -> best rank 0
        // W3: A rank 1, B rank 0 -> best rank 0
        // W4: A rank 2, B rank 1 -> best rank 1
        // W5: only in B at rank 2 -> best rank 2
        // Sorted by best rank, then by ID for ties:
        // rank 0: W2, W3 (tie broken alphabetically)
        // rank 1: W4
        // rank 2: W5
        Assert.Equal(4, group.PooledPreferences.Count);
        Assert.Equal("W2", group.PooledPreferences[0]);
        Assert.Equal("W3", group.PooledPreferences[1]);
        Assert.Equal("W4", group.PooledPreferences[2]);
        Assert.Equal("W5", group.PooledPreferences[3]);
    }

    // ---------------------------------------------------------------
    // 21. FriendGroups — Mutual Trio (Circular A→B, B→C, C→A)
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_MutualTrio_CircularBecomesAllSolo()
    {
        // A→B, B→C, C→A forms a circular chain, but each individual
        // reference is non-mutual (A→B but B→C, not B→A)
        // Current implementation requires BIDIRECTIONAL mutual references
        var workshops = TestHelpers.StandardWorkshops();
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),  // A references B
            P("B", Prefs("W2", "W3", "W4"), friendId: "C"),  // B references C (not A)
            P("C", Prefs("W2", "W3", "W4"), friendId: "A"),  // C references A (not B)
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // All three are non-mutual: A→B (B→C≠A), B→C (C→A≠B), C→A (A→B≠C)
        // Each becomes a solo group
        Assert.Equal(3, result.InputData.FriendGroups.Count);
        Assert.All(result.InputData.FriendGroups, g => Assert.Single(g.MemberIds));

        // Three non-mutual warnings (one for each person)
        var nonMutualWarnings = result.Warnings.Where(w => w.Category == WarningCategory.NonMutualFriend).ToList();
        Assert.Equal(3, nonMutualWarnings.Count);
    }

    // ---------------------------------------------------------------
    // 22. FriendGroups — Mutual Quad (4 people, all mutual pairs)
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_MutualQuad_SplitWithWarning()
    {
        // To create a 4-person connected group with single FriendId per person,
        // we use a chain where mutual detection creates a connected component.
        // A↔B (mutual pair), C↔D (mutual pair) - but these are separate groups.
        //
        // To connect them: A↔B, B↔C, C↔D creates:
        // A→B mutual (B→? must be A for mutual, but we need B→C to connect to C)
        //
        // Actually, with single FriendId, we can only have mutual PAIRS.
        // A 4-person "group" requires a chain: A→B, B→A would be mutual pair,
        // but to extend to C and D, we need non-mutual refs which break the chain.
        //
        // Test scenario: Create 4 persons where BFS would connect them into one group
        // by exploiting reverse lookup (if someone references a member, they get added).
        // But reverse lookup only adds if NOT in nonMutualPersons set.
        //
        // Alternative: A→B, B→A (mutual), C→A (non-mutual adds C to nonMutual), D→C (non-mutual)
        // This won't create a 4-person group either.
        //
        // Simplest scenario that COULD create oversized group:
        // If we had no non-mutual detection, A→B→C→D chain would create 4-group via BFS.
        // But with non-mutual detection, they all become solo.
        //
        // For this test: verify that 4+ people in a mutual chain trigger OversizedGroup warning.
        // We need a TRUE mutual connected group of 4, which requires creative linking.
        //
        // ACTUAL TEST: Use two mutual pairs that share a common member somehow?
        // Not possible with single FriendId.
        //
        // Let's test what happens with 4-way attempt: A↔B, C↔D (two separate pairs)
        var workshops = TestHelpers.StandardWorkshops();
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4"), friendId: "A"),  // A↔B mutual pair
            P("C", Prefs("W2", "W3", "W4"), friendId: "D"),
            P("D", Prefs("W2", "W3", "W4"), friendId: "C"),  // C↔D mutual pair
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Two separate mutual pairs, not one oversized group
        Assert.Equal(2, result.InputData.FriendGroups.Count);
        Assert.All(result.InputData.FriendGroups, g => Assert.Equal(2, g.MemberIds.Count));

        // No oversized warning (each group is size 2, not >3)
        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.OversizedGroup);

        // No non-mutual warnings (all pairs are bidirectional)
        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.NonMutualFriend);
    }

    // ---------------------------------------------------------------
    // 23. FriendGroups — Already In Group (C→B but B is paired with A)
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_AlreadyInGroup_RemoveRefAndWarn()
    {
        // A↔B is a mutual pair
        // C→B: C wants to join B, but B→A (not C), so C→B is non-mutual
        //
        // Only the initiator (C) is poisoned — the target (B) keeps its
        // valid mutual pair with A. Result: A-B group preserved, C goes solo.
        var workshops = TestHelpers.StandardWorkshops();
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4"), friendId: "A"),  // A↔B mutual pair preserved
            P("C", Prefs("W2", "W3", "W4"), friendId: "B"),  // C→B non-mutual, only C goes solo
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Two groups: A-B pair preserved, C goes solo
        Assert.Equal(2, result.InputData.FriendGroups.Count);

        // Find the A-B group (size 2) and the C group (size 1)
        var pairGroup = result.InputData.FriendGroups.Single(g => g.MemberIds.Count == 2);
        var soloGroup = result.InputData.FriendGroups.Single(g => g.MemberIds.Count == 1);

        Assert.Contains("A", pairGroup.MemberIds);
        Assert.Contains("B", pairGroup.MemberIds);
        Assert.Equal("C", soloGroup.MemberIds.Single());

        // Warning about non-mutual reference (C→B) — mentions both for transparency
        Assert.Contains(result.Warnings, w =>
            w.Category == WarningCategory.NonMutualFriend &&
            w.Message.Contains("C") &&
            w.Message.Contains("B"));
    }

    // ---------------------------------------------------------------
    // CROSS-FILE WORKSHOP VALIDATION TESTS
    // ---------------------------------------------------------------
    // Per IMPORT_WORKFLOW_SPEC.md: When a dedicated workshops file exists (source of truth),
    // persons files should be validated against it via DataService.ValidateCrossFileWorkshops:
    // - Matching workshops: no warning
    // - Different workshop data (Name/Type/Capacity/MinCapacity): warn (WorkshopDataMismatch)
    // - Missing workshops in persons file: warn (MissingWorkshops)
    // - Extra workshops in persons file: warn and ignore (ExtraWorkshopIgnored)
    // Location differences are intentionally not flagged.
    // ---------------------------------------------------------------

    [Fact]
    public void CrossFile_PersonsMatchesWorkshops_NoWarning()
    {
        // Arrange: Workshops from dedicated file
        var mainWorkshops = new List<Workshop>
        {
            new("W001", "Workshop A", WorkshopType.Type2, 20, 5, null, "workshops.xlsx"),
            new("W002", "Workshop B", WorkshopType.Type3, 25, 5, null, "workshops.xlsx"),
        };

        // Workshops embedded in persons file (matching data)
        var personsFileWorkshops = new List<Workshop>
        {
            new("W001", "Workshop A", WorkshopType.Type2, 20, 5, null, "persons.xlsx"),
            new("W002", "Workshop B", WorkshopType.Type3, 25, 5, null, "persons.xlsx"),
        };

        // Act
        var warnings = _svc.ValidateCrossFileWorkshops(mainWorkshops, personsFileWorkshops);

        // Assert: No warnings when data matches
        Assert.Empty(warnings);
    }

    [Fact]
    public void CrossFile_PersonsDifferentWorkshopData_WarnsAndIgnores()
    {
        // Arrange: Workshops from dedicated file (source of truth)
        var mainWorkshops = new List<Workshop>
        {
            new("W001", "Workshop A", WorkshopType.Type2, 20, 5, null, "workshops.xlsx"),
        };

        // Persons file has different capacity for same workshop ID
        var personsFileWorkshops = new List<Workshop>
        {
            new("W001", "Workshop A", WorkshopType.Type2, 30, 5, null, "persons.xlsx"), // capacity differs
        };

        // Act
        var warnings = _svc.ValidateCrossFileWorkshops(mainWorkshops, personsFileWorkshops);

        // Assert: Should warn about the difference
        Assert.Single(warnings);
        Assert.Equal(WarningCategory.WorkshopDataMismatch, warnings[0].Category);
        Assert.Contains("W001", warnings[0].Message);
        Assert.Contains("persons.xlsx", warnings[0].Message);
    }

    [Fact]
    public void CrossFile_PersonsMissingWorkshops_Warns()
    {
        // Arrange: Main workshops file has three workshops
        var mainWorkshops = new List<Workshop>
        {
            new("W001", "Workshop A", WorkshopType.Type2, 20, 5, null, "workshops.xlsx"),
            new("W002", "Workshop B", WorkshopType.Type3, 25, 5, null, "workshops.xlsx"),
            new("W003", "Workshop C", WorkshopType.Type4, 15, 3, null, "workshops.xlsx"),
        };

        // Persons file only has W001
        var personsFileWorkshops = new List<Workshop>
        {
            new("W001", "Workshop A", WorkshopType.Type2, 20, 5, null, "persons.xlsx"),
        };

        // Act
        var warnings = _svc.ValidateCrossFileWorkshops(mainWorkshops, personsFileWorkshops);

        // Assert: Should warn about missing W002 and W003
        Assert.Single(warnings);
        Assert.Equal(WarningCategory.MissingWorkshops, warnings[0].Category);
        Assert.Contains("W002", warnings[0].Message);
        Assert.Contains("W003", warnings[0].Message);
    }

    [Fact]
    public void CrossFile_PersonsExtraWorkshops_WarnsAndIgnores()
    {
        // Arrange: Main workshops file has only W001
        var mainWorkshops = new List<Workshop>
        {
            new("W001", "Workshop A", WorkshopType.Type2, 20, 5, null, "workshops.xlsx"),
        };

        // Persons file has W001 and W002 (extra)
        var personsFileWorkshops = new List<Workshop>
        {
            new("W001", "Workshop A", WorkshopType.Type2, 20, 5, null, "persons.xlsx"),
            new("W002", "Workshop B", WorkshopType.Type3, 25, 5, null, "persons.xlsx"), // extra
        };

        // Act
        var warnings = _svc.ValidateCrossFileWorkshops(mainWorkshops, personsFileWorkshops);

        // Assert: Should warn about extra W002 being ignored
        Assert.Single(warnings);
        Assert.Equal(WarningCategory.ExtraWorkshopIgnored, warnings[0].Category);
        Assert.Contains("W002", warnings[0].Message);
    }

    // ---------------------------------------------------------------
    // 26. FriendGroups — NonMutual Does Not Break Valid Mutual Pair
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_NonMutual_DoesNotBreak_ValidMutualPair()
    {
        // THIS IS THE KEY REGRESSION TEST for the non-mutual friend poisoning bug fix.
        //
        // Scenario: A↔B is a valid mutual pair (both reference each other).
        //           C→B is a one-way (non-mutual) reference.
        //
        // BUG (before fix): When detecting C→B as non-mutual, BOTH C and B were
        // added to nonMutualPersons. This "poisoned" B, breaking the valid A↔B pair.
        // Result: all three became solo groups — WRONG.
        //
        // FIX: Only the initiator (C) is added to nonMutualPersons, not the target (B).
        // This preserves the valid A↔B mutual pair while correctly making C solo.
        //
        // Expected after fix:
        //   - A and B form a group of 2 (mutual pair preserved)
        //   - C is a solo group (non-mutual initiator)
        //   - One NonMutualFriend warning for C→B
        var workshops = new List<Workshop>
        {
            W("W2", WorkshopType.Type2),
            W("W3", WorkshopType.Type3),
            W("W4", WorkshopType.Type4),
        };
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4"), friendId: "A"),  // A↔B mutual pair
            P("C", Prefs("W2", "W3", "W4"), friendId: "B"),  // C→B one-way (B→A, not B→C)
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // After fix: A-B pair preserved, C is solo → 2 groups total
        Assert.Equal(2, result.InputData.FriendGroups.Count);

        // Find the pair group (size 2) and verify it contains A and B
        var pairGroup = result.InputData.FriendGroups.FirstOrDefault(g => g.MemberIds.Count == 2);
        Assert.NotNull(pairGroup);
        Assert.Contains("A", pairGroup.MemberIds);
        Assert.Contains("B", pairGroup.MemberIds);

        // Find the solo group and verify it contains C
        var soloGroup = result.InputData.FriendGroups.FirstOrDefault(g => g.MemberIds.Count == 1);
        Assert.NotNull(soloGroup);
        Assert.Equal("C", soloGroup.MemberIds[0]);

        // Exactly one NonMutualFriend warning for C→B
        var nonMutualWarnings = result.Warnings
            .Where(w => w.Category == WarningCategory.NonMutualFriend)
            .ToList();
        Assert.Single(nonMutualWarnings);
        Assert.Contains("C", nonMutualWarnings[0].Message);
    }

    // ---------------------------------------------------------------
    // 27. FriendGroups — Multiple NonMutual Pointers, Mutual Pair Preserved
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_NonMutual_MultiplePointers_MutualPairPreserved()
    {
        // Extended version of the poisoning regression test.
        // A↔B is a valid mutual pair.
        // C→B AND D→B are both one-way references to B.
        //
        // After fix: Only C and D are added to nonMutualPersons (initiators only).
        // B is NOT poisoned, so A↔B mutual pair is preserved.
        //
        // Expected:
        //   - A and B form a group of 2 (mutual pair intact despite two external pointers)
        //   - C is a solo group
        //   - D is a solo group
        //   - Two NonMutualFriend warnings (one for C→B, one for D→B)
        var workshops = new List<Workshop>
        {
            W("W2", WorkshopType.Type2),
            W("W3", WorkshopType.Type3),
            W("W4", WorkshopType.Type4),
        };
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4"), friendId: "A"),  // A↔B mutual pair
            P("C", Prefs("W2", "W3", "W4"), friendId: "B"),  // C→B one-way
            P("D", Prefs("W2", "W3", "W4"), friendId: "B"),  // D→B one-way
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // 3 groups total: A-B pair + C solo + D solo
        Assert.Equal(3, result.InputData.FriendGroups.Count);

        // A-B pair preserved
        var pairGroup = result.InputData.FriendGroups.FirstOrDefault(g => g.MemberIds.Count == 2);
        Assert.NotNull(pairGroup);
        Assert.Contains("A", pairGroup.MemberIds);
        Assert.Contains("B", pairGroup.MemberIds);

        // C and D are each in solo groups
        var soloGroups = result.InputData.FriendGroups.Where(g => g.MemberIds.Count == 1).ToList();
        Assert.Equal(2, soloGroups.Count);
        var soloIds = soloGroups.Select(g => g.MemberIds[0]).ToHashSet();
        Assert.Contains("C", soloIds);
        Assert.Contains("D", soloIds);

        // Two NonMutualFriend warnings (C→B and D→B)
        var nonMutualWarnings = result.Warnings
            .Where(w => w.Category == WarningCategory.NonMutualFriend)
            .ToList();
        Assert.Equal(2, nonMutualWarnings.Count);
    }

    // ---------------------------------------------------------------
    // 28. FriendGroups — NonMutual, No Mutual Pair, Both Solo
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_NonMutual_NoMutualPair_BothSolo()
    {
        // C→B one-way, but B has NO friend reference at all.
        // There is no mutual pair to protect — B is simply a target of a one-way reference.
        //
        // Expected:
        //   - C is solo (non-mutual initiator)
        //   - B is solo (no friend reference, so just a regular person)
        //   - One NonMutualFriend warning for C→B
        var workshops = new List<Workshop>
        {
            W("W2", WorkshopType.Type2),
            W("W3", WorkshopType.Type3),
            W("W4", WorkshopType.Type4),
        };
        var persons = new List<Person>
        {
            P("B", Prefs("W2", "W3", "W4")),                  // B has no friend reference
            P("C", Prefs("W2", "W3", "W4"), friendId: "B"),   // C→B one-way
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Both persons become solo groups
        Assert.Equal(2, result.InputData.FriendGroups.Count);
        Assert.All(result.InputData.FriendGroups, g => Assert.Single(g.MemberIds));

        // Verify both are present
        var memberIds = result.InputData.FriendGroups.SelectMany(g => g.MemberIds).ToHashSet();
        Assert.Contains("B", memberIds);
        Assert.Contains("C", memberIds);

        // One NonMutualFriend warning for C→B
        var nonMutualWarnings = result.Warnings
            .Where(w => w.Category == WarningCategory.NonMutualFriend)
            .ToList();
        Assert.Single(nonMutualWarnings);
        Assert.Contains("C", nonMutualWarnings[0].Message);
        Assert.Contains("B", nonMutualWarnings[0].Message);
    }
}
