using WorkshopAssignment.Models;
using WorkshopAssignment.Services;
using Xunit;

namespace WorkshopAssignment.Tests;

public class DataServiceTests
{
    private readonly DataService _svc = new();

    // ---------------------------------------------------------------
    //  Helper: quick workshop constructors
    // ---------------------------------------------------------------
    private static Workshop W(string id, WorkshopType type, int cap = 20)
        => new(id, $"Workshop {id}", type, cap);

    private static Person P(string id, List<string> preferences, string? friendId = null)
        => new(id, $"Person {id}", preferences, friendId);

    /// <summary>
    /// Shorthand for creating a preference list from individual workshop IDs.
    /// Usage: Prefs("W2", "W3", "W4", "W1", "W5", "W6") returns List&lt;string&gt; with 6 ranked preferences.
    /// </summary>
    private static List<string> Prefs(params string[] ids)
        => ids.ToList();

    // ---------------------------------------------------------------
    //  1. BuildAssignmentInput — Valid Input
    // ---------------------------------------------------------------
    [Fact]
    public void BuildAssignmentInput_ValidInput_ReturnsResult()
    {
        var workshops = TestHelpers.StandardWorkshops();
        var persons = TestHelpers.StandardPersons();

        var result = _svc.BuildAssignmentInput(workshops, persons);

        Assert.NotNull(result);
        Assert.NotNull(result.InputData);
        Assert.Equal(workshops.Count, result.InputData.Workshops.Count);
        Assert.Equal(persons.Count, result.InputData.Persons.Count);
        Assert.NotEmpty(result.InputData.FriendGroups);

        // P1 and P2 are mutual friends -> should be in one group
        var groupWithP1 = result.InputData.FriendGroups
            .FirstOrDefault(g => g.MemberIds.Contains("P1"));
        Assert.NotNull(groupWithP1);
        Assert.Contains("P2", groupWithP1.MemberIds);
    }

    // ---------------------------------------------------------------
    //  2. BuildAssignmentInput — Empty Input
    // ---------------------------------------------------------------
    [Fact]
    public void BuildAssignmentInput_EmptyInput_ReturnsEmpty()
    {
        var result = _svc.BuildAssignmentInput([], []);

        Assert.NotNull(result);
        Assert.Empty(result.InputData.Workshops);
        Assert.Empty(result.InputData.Persons);
        Assert.Empty(result.InputData.FriendGroups);
        // Empty input to DataService does not generate warnings
        // (EmptySheet warnings are generated by ExcelService during file load, not here)
        Assert.Empty(result.Warnings);
    }

    // ---------------------------------------------------------------
    //  3. FriendGroups — Simple Pair Resolved
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_SimplePair_Resolved()
    {
        var workshops = new List<Workshop> { W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3), W("W4", WorkshopType.Type4) };
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4"), friendId: "A"),
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Should be exactly one group of 2
        Assert.Single(result.InputData.FriendGroups);
        var group = result.InputData.FriendGroups[0];
        Assert.Equal(2, group.MemberIds.Count);
        Assert.Contains("A", group.MemberIds);
        Assert.Contains("B", group.MemberIds);
    }

    // ---------------------------------------------------------------
    //  4. FriendGroups — Chain A-B-C (connected component -> one group of 3)
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_Chain_ABC()
    {
        // A->B->C is a friend chain. FriendId is an undirected edge regardless of
        // reciprocity, so A-B and B-C connect all three into one component. Connected-
        // component grouping resolves it to a single group [A,B,C] (business rule
        // 03ad9bd4: "A->B->C becomes group [A,B,C]"). The old mutual-pairs-only policy
        // wrongly emitted three solo groups here.
        var workshops = new List<Workshop> { W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3), W("W4", WorkshopType.Type4) };
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4"), friendId: "C"),
            P("C", Prefs("W2", "W3", "W4")),
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Exactly one group containing all three — no split (size 3 == max).
        Assert.Single(result.InputData.FriendGroups);
        var group = result.InputData.FriendGroups[0];
        Assert.Equal(3, group.MemberIds.Count);
        Assert.Contains("A", group.MemberIds);
        Assert.Contains("B", group.MemberIds);
        Assert.Contains("C", group.MemberIds);

        // No NonMutualFriend warning any more (mutual-pairs-only policy removed),
        // and no oversized split for a 3-member component.
        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.NonMutualFriend);
        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.OversizedGroup);
    }

    // ---------------------------------------------------------------
    //  5. FriendGroups — Circular Pair (no infinite loop)
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_CircularPair_Resolved()
    {
        var workshops = new List<Workshop> { W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3), W("W4", WorkshopType.Type4) };
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4"), friendId: "A"),
        };

        // Should complete without infinite loop and produce a group of 2
        var result = _svc.BuildAssignmentInput(workshops, persons);

        Assert.Single(result.InputData.FriendGroups);
        Assert.Equal(2, result.InputData.FriendGroups[0].MemberIds.Count);
        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.OversizedGroup);
    }

    // ---------------------------------------------------------------
    //  6. FriendGroups — Self Reference (A->A)
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_SelfReference_Warning()
    {
        // DataService's BFS: A has FriendId="A". When processing A, FriendId "A" is already
        // visited, so it's a no-op. A ends up as a solo group.
        // Note: DataService does NOT emit SelfReference warnings — that is the ExcelService's job.
        // DataService treats self-ref as effectively "no friend" since BFS skips already-visited.
        var workshops = new List<Workshop> { W("W1", WorkshopType.Type1), W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3) };
        var persons = new List<Person>
        {
            P("A", Prefs("W1", "W2", "W3"), friendId: "A"),
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // A becomes a solo group
        Assert.Single(result.InputData.FriendGroups);
        Assert.Single(result.InputData.FriendGroups[0].MemberIds);
        Assert.Equal("A", result.InputData.FriendGroups[0].MemberIds[0]);
    }

    // ---------------------------------------------------------------
    //  7. FriendGroups — Cross-File References
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_CrossFileRefs_Resolved()
    {
        // Simulates persons merged from different files: A references B by ID, and B
        // (from another file) has no FriendId. The undirected edge A-B still groups
        // them into a single group of 2 — cross-file one-way references now resolve.
        var workshops = new List<Workshop> { W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3), W("W4", WorkshopType.Type4) };
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4")),  // B has no friendId — came from a different file
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Single group containing both.
        Assert.Single(result.InputData.FriendGroups);
        var group = result.InputData.FriendGroups[0];
        Assert.Equal(2, group.MemberIds.Count);
        Assert.Contains("A", group.MemberIds);
        Assert.Contains("B", group.MemberIds);

        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.NonMutualFriend);
    }

    // ---------------------------------------------------------------
    //  8. FriendGroups — Oversized Group Split (chain of 4)
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_OversizedGroup_Split()
    {
        var workshops = new List<Workshop> { W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3), W("W4", WorkshopType.Type4) };
        // Chain A->B->C->D. Undirected edges A-B, B-C, C-D connect all four into one
        // component of 4, which exceeds the max group size of 3. It splits into
        // consecutive subgroups of <=3 ordered stably by person Id: [A,B,C] + [D].
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4"), friendId: "C"),
            P("C", Prefs("W2", "W3", "W4"), friendId: "D"),
            P("D", Prefs("W2", "W3", "W4")),
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Splits into a group of 3 and a group of 1.
        Assert.Equal(2, result.InputData.FriendGroups.Count);

        var tripleGroup = result.InputData.FriendGroups.Single(g => g.MemberIds.Count == 3);
        Assert.Contains("A", tripleGroup.MemberIds);
        Assert.Contains("B", tripleGroup.MemberIds);
        Assert.Contains("C", tripleGroup.MemberIds);

        var soloGroup = result.InputData.FriendGroups.Single(g => g.MemberIds.Count == 1);
        Assert.Equal("D", soloGroup.MemberIds.Single());

        // Exactly one OversizedGroup warning; the split path is what this test exercises.
        Assert.Single(result.Warnings.Where(w => w.Category == WarningCategory.OversizedGroup));
        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.NonMutualFriend);
    }

    // ---------------------------------------------------------------
    //  9. FriendGroups — Reverse Lookup (referenced person joins the group)
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_ReverseLookup()
    {
        // A->B; B has no FriendId of its own. B is pulled into A's group by the
        // undirected edge (reverse direction) — they form a single group of 2.
        var workshops = new List<Workshop> { W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3), W("W4", WorkshopType.Type4) };
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4")),  // no friend-id set
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Single group with both members.
        Assert.Single(result.InputData.FriendGroups);
        var group = result.InputData.FriendGroups[0];
        Assert.Equal(2, group.MemberIds.Count);
        Assert.Contains("A", group.MemberIds);
        Assert.Contains("B", group.MemberIds);

        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.NonMutualFriend);
    }

    // ---------------------------------------------------------------
    // 10. FriendGroups — No Friends, All Solo
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_NoFriends_AllSolo()
    {
        var workshops = new List<Workshop> { W("W1", WorkshopType.Type1), W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3) };
        var persons = new List<Person>
        {
            P("A", Prefs("W1", "W2", "W3")),
            P("B", Prefs("W1", "W2", "W3")),
            P("C", Prefs("W1", "W2", "W3")),
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        Assert.Equal(3, result.InputData.FriendGroups.Count);
        Assert.All(result.InputData.FriendGroups, g => Assert.Single(g.MemberIds));
    }

    // ---------------------------------------------------------------
    // 11. FriendGroups — Invalid Friend Reference
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_InvalidFriendRef_Warning()
    {
        var workshops = new List<Workshop> { W("W1", WorkshopType.Type1), W("W2", WorkshopType.Type2), W("W3", WorkshopType.Type3) };
        var persons = new List<Person>
        {
            P("A", Prefs("W1", "W2", "W3"), friendId: "Z"),  // Z doesn't exist
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // A becomes solo group, with InvalidFriend warning
        Assert.Single(result.InputData.FriendGroups);
        Assert.Single(result.InputData.FriendGroups[0].MemberIds);
        Assert.Equal("A", result.InputData.FriendGroups[0].MemberIds[0]);
        Assert.Contains(result.Warnings, w => w.Category == WarningCategory.InvalidFriend);
        Assert.Contains(result.Warnings, w => w.Message.Contains("Z"));
    }

    // ---------------------------------------------------------------
    // 12. FriendGroups — Preference Pooling (Union with Best Rank)
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_PreferencePooling_UnionWithBestRank()
    {
        var workshops = new List<Workshop>
        {
            W("W2", WorkshopType.Type2),
            W("W3", WorkshopType.Type3),
            W("W4", WorkshopType.Type4),
            W("W5", WorkshopType.Type2),
        };
        var persons = new List<Person>
        {
            // A's preferences: W2 (rank 0), W3 (rank 1), W4 (rank 2)
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            // B's preferences: W3 (rank 0), W4 (rank 1), W5 (rank 2)
            P("B", Prefs("W3", "W4", "W5"), friendId: "A"),
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        Assert.Single(result.InputData.FriendGroups);
        var group = result.InputData.FriendGroups[0];

        // Pooled preferences: union of all unique workshop IDs, sorted by best rank.
        // W2: only in A at rank 0 -> best rank 0
        // W3: A rank 1, B rank 0 -> best rank 0
        // W4: A rank 2, B rank 1 -> best rank 1
        // W5: only in B at rank 2 -> best rank 2
        // Sorted by best rank, then by ID for ties:
        // rank 0: W2, W3 (tie broken alphabetically)
        // rank 1: W4
        // rank 2: W5
        Assert.Equal(4, group.PooledPreferences.Count);
        Assert.Equal("W2", group.PooledPreferences[0]);
        Assert.Equal("W3", group.PooledPreferences[1]);
        Assert.Equal("W4", group.PooledPreferences[2]);
        Assert.Equal("W5", group.PooledPreferences[3]);
    }

    // ---------------------------------------------------------------
    // 21. FriendGroups — Mutual Trio (Circular A->B->C->A -> one group of 3)
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_MutualTrio_Circular_ResolvesToOneGroup()
    {
        // A->B, B->C, C->A: three mutual friends. With a single FriendId per person,
        // a real trio can only be expressed as a CYCLE — no two people reciprocate
        // directly. Treating FriendId as an undirected edge, the cycle is one connected
        // component that resolves to a SINGLE group of 3 (business rule 03ad9bd4:
        // "circular references are valid and resolved"). This is the reported-bug shape;
        // the old mutual-pairs-only policy wrongly split it into three solo groups.
        var workshops = TestHelpers.StandardWorkshops();
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),  // A references B
            P("B", Prefs("W2", "W3", "W4"), friendId: "C"),  // B references C
            P("C", Prefs("W2", "W3", "W4"), friendId: "A"),  // C references A
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // One group containing all three.
        Assert.Single(result.InputData.FriendGroups);
        var group = result.InputData.FriendGroups[0];
        Assert.Equal(3, group.MemberIds.Count);
        Assert.Contains("A", group.MemberIds);
        Assert.Contains("B", group.MemberIds);
        Assert.Contains("C", group.MemberIds);

        // No NonMutualFriend warnings (policy removed) and no oversized split.
        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.NonMutualFriend);
        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.OversizedGroup);
    }

    // ---------------------------------------------------------------
    // 22. FriendGroups — Two Separate Mutual Pairs Stay Independent
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_TwoSeparatePairs_StayIndependent()
    {
        // A<->B and C<->D are two independent mutual pairs with no edge between them.
        // They are two separate connected components -> two groups of 2. No component
        // exceeds the cap, so there is no OversizedGroup split.
        var workshops = TestHelpers.StandardWorkshops();
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4"), friendId: "A"),  // A<->B mutual pair
            P("C", Prefs("W2", "W3", "W4"), friendId: "D"),
            P("D", Prefs("W2", "W3", "W4"), friendId: "C"),  // C<->D mutual pair
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Two separate groups, each of size 2.
        Assert.Equal(2, result.InputData.FriendGroups.Count);
        Assert.All(result.InputData.FriendGroups, g => Assert.Equal(2, g.MemberIds.Count));

        // No oversized split and no NonMutualFriend warnings.
        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.OversizedGroup);
        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.NonMutualFriend);
    }

    // ---------------------------------------------------------------
    // 23. FriendGroups — One-Way Pointer Into a Mutual Pair (joins the group)
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_OneWayIntoMutualPair_FormsGroupOfThree()
    {
        // A<->B are a mutual pair; C->B is a one-way reference into that pair.
        // FriendId is an undirected edge, so C-B connects C to the {A,B} component:
        // all three form ONE group of 3. (Under the removed mutual-pairs-only policy,
        // C was forced solo and only A-B stayed together.)
        var workshops = TestHelpers.StandardWorkshops();
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4"), friendId: "A"),  // A<->B mutual pair
            P("C", Prefs("W2", "W3", "W4"), friendId: "B"),  // C->B one-way, still joins
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Single group with all three members.
        Assert.Single(result.InputData.FriendGroups);
        var group = result.InputData.FriendGroups[0];
        Assert.Equal(3, group.MemberIds.Count);
        Assert.Contains("A", group.MemberIds);
        Assert.Contains("B", group.MemberIds);
        Assert.Contains("C", group.MemberIds);

        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.NonMutualFriend);
        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.OversizedGroup);
    }

    // ---------------------------------------------------------------
    // CROSS-FILE WORKSHOP VALIDATION TESTS
    // ---------------------------------------------------------------
    // Per IMPORT_WORKFLOW_SPEC.md: When a dedicated workshops file exists (source of truth),
    // persons files should be validated against it via DataService.ValidateCrossFileWorkshops:
    // - Matching workshops: no warning
    // - Different workshop data (Name/Type/Capacity/MinCapacity): warn (WorkshopDataMismatch)
    // - Missing workshops in persons file: warn (MissingWorkshops)
    // - Extra workshops in persons file: warn and ignore (ExtraWorkshopIgnored)
    // Location differences are intentionally not flagged.
    // ---------------------------------------------------------------

    [Fact]
    public void CrossFile_PersonsMatchesWorkshops_NoWarning()
    {
        // Arrange: Workshops from dedicated file
        var mainWorkshops = new List<Workshop>
        {
            new("W001", "Workshop A", WorkshopType.Type2, 20, 5, null, "workshops.xlsx"),
            new("W002", "Workshop B", WorkshopType.Type3, 25, 5, null, "workshops.xlsx"),
        };

        // Workshops embedded in persons file (matching data)
        var personsFileWorkshops = new List<Workshop>
        {
            new("W001", "Workshop A", WorkshopType.Type2, 20, 5, null, "persons.xlsx"),
            new("W002", "Workshop B", WorkshopType.Type3, 25, 5, null, "persons.xlsx"),
        };

        // Act
        var warnings = _svc.ValidateCrossFileWorkshops(mainWorkshops, personsFileWorkshops);

        // Assert: No warnings when data matches
        Assert.Empty(warnings);
    }

    [Fact]
    public void CrossFile_PersonsDifferentWorkshopData_WarnsAndIgnores()
    {
        // Arrange: Workshops from dedicated file (source of truth)
        var mainWorkshops = new List<Workshop>
        {
            new("W001", "Workshop A", WorkshopType.Type2, 20, 5, null, "workshops.xlsx"),
        };

        // Persons file has different capacity for same workshop ID
        var personsFileWorkshops = new List<Workshop>
        {
            new("W001", "Workshop A", WorkshopType.Type2, 30, 5, null, "persons.xlsx"), // capacity differs
        };

        // Act
        var warnings = _svc.ValidateCrossFileWorkshops(mainWorkshops, personsFileWorkshops);

        // Assert: Should warn about the difference
        Assert.Single(warnings);
        Assert.Equal(WarningCategory.WorkshopDataMismatch, warnings[0].Category);
        Assert.Contains("W001", warnings[0].Message);
        Assert.Contains("persons.xlsx", warnings[0].Message);
    }

    [Fact]
    public void CrossFile_PersonsMissingWorkshops_Warns()
    {
        // Arrange: Main workshops file has three workshops
        var mainWorkshops = new List<Workshop>
        {
            new("W001", "Workshop A", WorkshopType.Type2, 20, 5, null, "workshops.xlsx"),
            new("W002", "Workshop B", WorkshopType.Type3, 25, 5, null, "workshops.xlsx"),
            new("W003", "Workshop C", WorkshopType.Type4, 15, 3, null, "workshops.xlsx"),
        };

        // Persons file only has W001
        var personsFileWorkshops = new List<Workshop>
        {
            new("W001", "Workshop A", WorkshopType.Type2, 20, 5, null, "persons.xlsx"),
        };

        // Act
        var warnings = _svc.ValidateCrossFileWorkshops(mainWorkshops, personsFileWorkshops);

        // Assert: Should warn about missing W002 and W003
        Assert.Single(warnings);
        Assert.Equal(WarningCategory.MissingWorkshops, warnings[0].Category);
        Assert.Contains("W002", warnings[0].Message);
        Assert.Contains("W003", warnings[0].Message);
    }

    [Fact]
    public void CrossFile_PersonsExtraWorkshops_WarnsAndIgnores()
    {
        // Arrange: Main workshops file has only W001
        var mainWorkshops = new List<Workshop>
        {
            new("W001", "Workshop A", WorkshopType.Type2, 20, 5, null, "workshops.xlsx"),
        };

        // Persons file has W001 and W002 (extra)
        var personsFileWorkshops = new List<Workshop>
        {
            new("W001", "Workshop A", WorkshopType.Type2, 20, 5, null, "persons.xlsx"),
            new("W002", "Workshop B", WorkshopType.Type3, 25, 5, null, "persons.xlsx"), // extra
        };

        // Act
        var warnings = _svc.ValidateCrossFileWorkshops(mainWorkshops, personsFileWorkshops);

        // Assert: Should warn about extra W002 being ignored
        Assert.Single(warnings);
        Assert.Equal(WarningCategory.ExtraWorkshopIgnored, warnings[0].Category);
        Assert.Contains("W002", warnings[0].Message);
    }

    // ---------------------------------------------------------------
    // 26. FriendGroups — Three-Cycle Regression (P1->P2->P3->P1)
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_ThreeCycle_P1P2P3_ResolvesToSingleGroupOfThree()
    {
        // REGRESSION TEST for the reported bug: a mutual friend trio got split across
        // three different workshops. Root cause: a single FriendId per person means three
        // mutual friends can only form a CYCLE (P1->P2->P3->P1) where no two reciprocate
        // directly. The old mutual-pairs-only policy flagged all three as non-mutual and
        // forced each to a solo group; the solver (atomic per group) then placed them
        // apart. Connected-component grouping over the undirected friendship graph keeps
        // the cycle together as one group of 3.
        var workshops = new List<Workshop>
        {
            W("W2", WorkshopType.Type2),
            W("W3", WorkshopType.Type3),
            W("W4", WorkshopType.Type4),
        };
        var persons = new List<Person>
        {
            P("P1", Prefs("W2", "W3", "W4"), friendId: "P2"),  // P1 -> P2
            P("P2", Prefs("W2", "W3", "W4"), friendId: "P3"),  // P2 -> P3
            P("P3", Prefs("W2", "W3", "W4"), friendId: "P1"),  // P3 -> P1 (closes the cycle)
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // The three friends land in exactly ONE group of three.
        Assert.Single(result.InputData.FriendGroups);
        var group = result.InputData.FriendGroups[0];
        Assert.Equal(3, group.MemberIds.Count);
        Assert.Contains("P1", group.MemberIds);
        Assert.Contains("P2", group.MemberIds);
        Assert.Contains("P3", group.MemberIds);

        // Preferences are pooled so the solver can place the whole trio together.
        Assert.NotEmpty(group.PooledPreferences);

        // No NonMutualFriend warning (mutual-pairs-only policy removed) and no split.
        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.NonMutualFriend);
        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.OversizedGroup);
    }

    // ---------------------------------------------------------------
    // 27. FriendGroups — Star Component Exceeds Cap, Splits Deterministically
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_StarComponent_ExceedsCap_SplitsDeterministically()
    {
        // A<->B mutual, plus C->B and D->B: all four are one connected component
        // (a star centred on B). That exceeds the max group size of 3, so it is split
        // into consecutive subgroups of <=3 ordered stably by person Id: [A,B,C] + [D].
        // One OversizedGroup warning is emitted. (Old policy: A-B pair + C solo + D solo.)
        var workshops = new List<Workshop>
        {
            W("W2", WorkshopType.Type2),
            W("W3", WorkshopType.Type3),
            W("W4", WorkshopType.Type4),
        };
        var persons = new List<Person>
        {
            P("A", Prefs("W2", "W3", "W4"), friendId: "B"),
            P("B", Prefs("W2", "W3", "W4"), friendId: "A"),  // A<->B mutual pair
            P("C", Prefs("W2", "W3", "W4"), friendId: "B"),  // C->B one-way
            P("D", Prefs("W2", "W3", "W4"), friendId: "B"),  // D->B one-way
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Component of 4 splits into a group of 3 and a group of 1.
        Assert.Equal(2, result.InputData.FriendGroups.Count);

        // Deterministic split by person Id (ordinal): [A,B,C] together, D alone.
        var tripleGroup = result.InputData.FriendGroups.Single(g => g.MemberIds.Count == 3);
        Assert.Contains("A", tripleGroup.MemberIds);
        Assert.Contains("B", tripleGroup.MemberIds);
        Assert.Contains("C", tripleGroup.MemberIds);

        var soloGroup = result.InputData.FriendGroups.Single(g => g.MemberIds.Count == 1);
        Assert.Equal("D", soloGroup.MemberIds.Single());

        // Exactly one OversizedGroup warning; no NonMutualFriend warnings.
        Assert.Single(result.Warnings.Where(w => w.Category == WarningCategory.OversizedGroup));
        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.NonMutualFriend);
    }

    // ---------------------------------------------------------------
    // 28. FriendGroups — One-Way Reference Forms a Group of Two
    // ---------------------------------------------------------------
    [Fact]
    public void FriendGroups_OneWayRef_FormsGroupOfTwo()
    {
        // C->B one-way; B names no one. FriendId is an undirected edge, so C-B still
        // groups them: they form a single group of 2. (Old mutual-pairs-only policy
        // wrongly emitted two solo groups plus a NonMutualFriend warning.)
        var workshops = new List<Workshop>
        {
            W("W2", WorkshopType.Type2),
            W("W3", WorkshopType.Type3),
            W("W4", WorkshopType.Type4),
        };
        var persons = new List<Person>
        {
            P("B", Prefs("W2", "W3", "W4")),                  // B names no friend
            P("C", Prefs("W2", "W3", "W4"), friendId: "B"),   // C->B one-way
        };

        var result = _svc.BuildAssignmentInput(workshops, persons);

        // Single group containing both.
        Assert.Single(result.InputData.FriendGroups);
        var group = result.InputData.FriendGroups[0];
        Assert.Equal(2, group.MemberIds.Count);
        Assert.Contains("B", group.MemberIds);
        Assert.Contains("C", group.MemberIds);

        // No NonMutualFriend warning any more.
        Assert.DoesNotContain(result.Warnings, w => w.Category == WarningCategory.NonMutualFriend);
    }
}
